### ISSUE TITLE
お問い合わせ Web-To-Case連携 調整

### ISSUE THREAD

**Issue by whitenia-shiraishi** [whitenia/worldplus-gym-service-site#1]
## テスト環境対象ページ
https://worldplus-gym.sub.jp/corporatemember/form.html

## Salesforce ケースオブジェクト
https://worldplus-gym--dev03.sandbox.lightning.force.com/lightning/o/Case/list?filterName=Recent
正しく処理されると↑に編集

## Web-to-Case HTML
[Sandbox_web_to_case.html.zip](https://github.com/whitenia/worldplus-gym-service-site/files/12583068/Sandbox_web_to_case.html.zip)

**Comment by ShinjiroMoriya** [comment]
↑法人のお問い合わせページですか？

**Comment by ShinjiroMoriya** [comment]
もらったhtmlの項目的に店舗へのお問い合わせだと思ってました。

一応やったので確認ください。
店舗からの遷移した場合のお問い合わせ
https://worldplus-gym.sub.jp/contact/form.html?shop=%E3%83%AF%E3%83%BC%E3%83%AB%E3%83%89%E3%83%97%E3%83%A9%E3%82%B9%E3%82%B8%E3%83%A0%20%E4%B9%85%E5%96%9C%E9%9D%92%E8%91%89%E5%BA%97

特になし
https://worldplus-gym.sub.jp/contact/form.html

店舗番号っていうものが取得できないのでCaseに連携できないです。

**Comment by ShinjiroMoriya** [comment]
作業したMTの画面
https://worldplus-gym.sub.jp/_mtadmin/mt.cgi?__mode=view&id=6&saved_changes=1&_type=content_data&type=content_data_2&blog_id=2&content_type_id=2

**Comment by whitenia-shiraishi** [comment]
すみません、店舗のお問い合わせが正しいです。
リンク間違えてました。

確認しますね。

**Comment by whitenia-shiraishi** [comment]
@ShinjiroMoriya 
20のうしろにある店舗名を店舗コードに入れて送っていただくことはできそうでしょうか？

![CleanShot 2023-09-14 at 19 21 26@2x](https://github.com/whitenia/worldplus-gym-service-site/assets/57860291/ba230eb2-76c3-4bd1-aa33-175cd5154a3e)

**Comment by ShinjiroMoriya** [comment]
いけますね。
全店舗、ワールドプラスジムの後に空白スペース入ってますかね。

**Comment by ShinjiroMoriya** [comment]
入れました。

**Comment by whitenia-shiraishi** [comment]
@ShinjiroMoriya 
見た感じ、全店舗入っていそうです！

**Comment by ShinjiroMoriya** [comment]
じゃあ大丈夫そうですね。

**Comment by whitenia-shiraishi** [comment]
@ShinjiroMoriya 
すみません、、1点だけお願いさせてください。

末尾に `店` というのが必ず入っているのですが、
`店` はのぞいて連携できますでしょうか？

**Comment by ShinjiroMoriya** [comment]
いけますよ。やっておきます。

**Comment by whitenia-shiraishi** [comment]
@ShinjiroMoriya 

すみません、本番にもつながるか検証したいとのことで、
以下、設定いただいた管理画面のコードを本番に連携されるようになおしたのですが、
うまく連携されず、、もしうまく設定できていないところがあったら教えていただけないでしょうか？

https://worldplus-gym.sub.jp/_mtadmin/mt.cgi?__mode=view&id=6&saved_changes=1&_type=content_data&type=content_data_2&blog_id=2&content_type_id=2

[本番用のweb to ケース (1).html.zip](https://github.com/whitenia/worldplus-gym-service-site/files/12678564/web.to.1.html.zip)

**Comment by ShinjiroMoriya** [comment]
本番のMTのログイン情報ください

**Comment by whitenia-shiraishi** [comment]
@ShinjiroMoriya 
いや、一旦開発組織MTから本番SF組織につないでみたいそうで、
守屋さんになおしてもらった開発組織MTの内容を修正していました。

**Comment by ShinjiroMoriya** [comment]
そういうことね。
STG確認してみます。

**Comment by ShinjiroMoriya** [comment]
生成されたhtmlそのままで送ってみましたがデータが届かないですね。
設定系が怪しいですが、どうですか？

**Comment by whitenia-shiraishi** [comment]
ありがとうございます！
なるほど、、ちょっと青木くんに設定みてもらいますね。

**Comment by ShinjiroMoriya** [comment]
デバッグモードでやってみたけど、
メッセージはキューに入りましたって受け付けしたっぽいけど、
データは入ってない。
<img width="703" alt="スクリーンショット 2023-09-21 16 12 45" src="https://github.com/whitenia/worldplus-gym-service-site/assets/7581596/6846576a-08a6-4c88-914e-e2542585b21c">

**Comment by whitenia-shiraishi** [comment]
@ShinjiroMoriya 
ケース作ったときに動作するフローがエラーになってました。
青木くんになおしてもらったので
お手数なのですが、再度デバッグ送信してみていただけないでしょうか？

**Comment by ShinjiroMoriya** [comment]
メールが届いたので入ったと思います。
ご確認ください。
stg環境では試してないです。

**Comment by whitenia-shiraishi** [comment]
無事に登録できてました、ありがとうございます！

**Comment by whitenia-shiraishi** [comment]
@ShinjiroMoriya 
先程はありがとうございました。
Salesforce側を青木くんに確認いただいているのですが、
一点テキスト調整をお願いさせてください。

以下の要素が修正後からなくなっているようで
お手数ですが調整をお願いしてもよいでしょうか？

```
必要事項をご記入のうえ、「内容確認へ」ボタンを押してください。
必須 は必須項目です。
```

![CleanShot 2023-10-02 at 15 35 35](https://github.com/whitenia/worldplus-gym-service-site/assets/57860291/e634ea99-5e7a-4939-a04b-a99ad43bf4c4)

**Comment by ShinjiroMoriya** [comment]
了解です。

**Comment by ShinjiroMoriya** [comment]
STGに反映済みです。
このタグを加えました。
<img width="842" alt="スクリーンショット 2023-10-03 9 16 22" src="https://github.com/whitenia/worldplus-gym-service-site/assets/7581596/cea76bd0-04f6-4753-a546-3d1df4628299">

デバッグ用のコードは削除しておきました。

**Comment by ShinjiroMoriya** [comment]
あとcss記述加えました。
こちらも反映お願いします。
<img width="377" alt="スクリーンショット 2023-10-03 9 19 47" src="https://github.com/whitenia/worldplus-gym-service-site/assets/7581596/c8842c30-dd96-491d-8207-2bfe8a24a640">

```
@media only screen and (max-width: 999px) {
  .formbox .aform-radio-ul {
    height: auto;
  }
}
```

**Comment by whitenia-shiraishi** [comment]
@ShinjiroMoriya 
見た目の調整ありがとうございます！
こちらで問題ないです。

ケースに連携されない件、開発環境で試していたのですが、
Web-to-Case のHTMLで送信した場合と
開発環境のサイトから送信した場合で
デバッグしたときに表示されるメッセージが少し異なっています。

調べてみるとこれによってうまくケースができないような
ことがありそうなので、Webから実施するとなぜこちらが出てくるのか、
調査いただけないでしょうか？

`ignore-captcha: Ignoring captcha since redirect timed out.`

僕のほうでも継続して調べているので、わかったことがあればご連絡します。

![CleanShot 2023-10-05 at 14 18 57](https://github.com/whitenia/worldplus-gym-service-site/assets/57860291/bed76692-794d-41b1-9662-061dd12bb01f)

**Comment by ShinjiroMoriya** [comment]
<img width="1436" alt="スクリーンショット 2023-10-05 17 18 28" src="https://github.com/whitenia/worldplus-gym-service-site/assets/7581596/cc2bd046-05c8-420e-ba70-c419cd266eb2">
フローが有効になってないから？

**Comment by ShinjiroMoriya** [comment]
<img width="684" alt="スクリーンショット 2023-10-05 17 28 57" src="https://github.com/whitenia/worldplus-gym-service-site/assets/7581596/7f7f6e8d-5da5-472e-8f38-f6d8c6617b41">

僕も試してみました。

`ignore-captcha: Ignoring captcha since redirect timed out.`
メッセージは出てないです。

**Comment by ShinjiroMoriya** [comment]
ignore-captcha: Ignoring captcha since redirect timed out.
このメッセージはbotを疑われている様です。
GPTに聞いたら
```
"ignore-captcha: Ignoring captcha since redirect timed out." というメッセージが
 "Web to Case" フォームで表示される場合、このメッセージはCAPTCHA (Completely Automated Public Turing test to tell Computers and Humans Apart) の処理に関連しています。
CAPTCHA は、ボットや自動化されたスクリプトからの不正な送信を防ぐためのセキュリティ対策の一環として使われます。
```

**Comment by ShinjiroMoriya** [comment]
本番で通常ユーザのお問い合わせが問題なくケースに入っていそうです。

テストする時はtest.co.jpとかではなく、それっぽいものを送信した方が良さそうです。

**Comment by whitenia-shiraishi** [comment]
@ShinjiroMoriya 
ありがとうございます！

そういうことですね。
適当なアドレスだったり、
何回も連続でやったりするから疑われてる感じですね。

原因が明らかになってよかったです。
こちらで本番リリースしたいと思います。

**Comment by whitenia-shiraishi** [comment]
@ShinjiroMoriya 
すみません、完了画面に以下の表示が出てしまっているので
非表示にできそうでしょうか？

![CleanShot 2023-10-06 at 07 49 38@2x](https://github.com/whitenia/worldplus-gym-service-site/assets/57860291/d2221e45-0a02-4227-b3ac-9b6b4179ad6a)

**Comment by ShinjiroMoriya** [comment]
stgに反映しました。

**Comment by whitenia-shiraishi** [comment]
@ShinjiroMoriya 
本番だけ、h1に店名が2つ出てきてしまっていて、
もし原因わかりそうなら助けていただけないでしょうか。

https://www.worldplus-gym.com/contact/form.html?shop=%E3%83%AF%E3%83%BC%E3%83%AB%E3%83%89%E3%83%97%E3%83%A9%E3%82%B9%E3%82%B8%E3%83%A0%20%E5%B2%B8%E9%87%8C%E5%BA%97

![CleanShot 2023-10-11 at 18 19 48](https://github.com/whitenia/worldplus-gym-service-site/assets/57860291/30ca436b-b630-41b1-a040-96195fdd00f6)

**Comment by ShinjiroMoriya** [comment]
<img width="545" alt="スクリーンショット 2023-10-11 19 21 06" src="https://github.com/whitenia/worldplus-gym-service-site/assets/7581596/724a32dd-e66e-4412-8162-b86262e98a64">
同じことやってるscriptが入ってますね。
僕が書いたものを消すか、
キャプチャのコードを消すかですね。

**Comment by ShinjiroMoriya** [comment]
これはstgには入ってないんですよね。
なんかあっても嫌なので、
僕が書いた方を消しておいてもらえますか？

stgはそのままでよいと思います。
下記赤い箇所。
<img width="695" alt="スクリーンショット 2023-10-11 19 23 37" src="https://github.com/whitenia/worldplus-gym-service-site/assets/7581596/9f8e1716-0f8c-47ed-8751-70025449153e">

**Comment by whitenia-shiraishi** [comment]
ありがとうございます！
調整できたのでクローズします。
