### ISSUE TITLE
一覧 & 詳細 & お知らせ - 店舗名の （コメ兵）表記を取り除く処理を入れたい

### ISSUE THREAD

**Issue by whitenia-shiraishi** [whitenia/worldplus-gym-service-site#14]
店名に含まれる（コメ兵）という文字列をトリたいという要望いただいています。

GBP上は（コメ兵）という文字を入れたいらしく、データ修正ができないので、
店名に含まれる（コメ兵）はトル処理をお願いしてもよいでしょうか？

![CleanShot 2024-02-29 at 12 41 31](https://github.com/whitenia/worldplus-gym-service-site/assets/57860291/d0298f5b-2bb9-4916-80a7-4e3e7531d2ae)

**Comment by ShinjiroMoriya** [comment]
了解です

**Comment by whitenia-shiraishi** [comment]
こちら登録するリポジトリ間違えてました。すみません。
OKですのでクローズします。
