### ISSUE TITLE
トップページ - デザイン改修の依頼

### ISSUE THREAD

**Issue by whitenia-shiraishi** [whitenia/worldplus-gym-service-site#2]
MTのテスト環境で調整をいただけますと幸いです。

## ご依頼事項説明動画
https://www.awesomescreenshot.com/video/24046087?key=0a4f35ca8e34415fbe4c697d9c26a9bd

## Figma
https://www.figma.com/file/wGFKu4XqlUy9fB8Rfw0w1Z/WorldPlus?type=design&node-id=6-2&mode=design&t=G0yHNyrUi51N2FBG-0

**Comment by ShinjiroMoriya** [comment]
devに反映しました。

**Comment by whitenia-shiraishi** [comment]
@ShinjiroMoriya 
こちらありがとうございます！

トップのビジュアルとメッセージを変更したくて、
取り急ぎこちら1つめだけ変えていただいてもよいでしょうか？
https://www.figma.com/file/wGFKu4XqlUy9fB8Rfw0w1Z/WorldPlus?type=design&node-id=1008-3685&mode=design&t=qI19ah97MldtZAOr-4

![image](https://github.com/whitenia/worldplus-gym-service-site/assets/57860291/2d6040dc-a8c8-4de1-8516-ec46f319658f)

**Comment by ShinjiroMoriya** [comment]
SPの画像も展開してください。

**Comment by ShinjiroMoriya** [comment]
変更しました。

**Comment by whitenia-shiraishi** [comment]
@ShinjiroMoriya 
ありがとうございます！
今日残りの画像について加嶋くんに準備してもらったら
差し替え依頼させてもらいますのでお手数ですがよろしくお願いします！

**Comment by whitenia-shiraishi** [comment]
@ShinjiroMoriya 
こちらありがとうございます！
残りのビジュアルについても調整できたので、
数字の①〜④の順番でスライドするように調整いただけるとありがたいです。

https://www.figma.com/file/wGFKu4XqlUy9fB8Rfw0w1Z/WorldPlus?type=design&node-id=1008-3685&mode=design&t=qI19ah97MldtZAOr-4

![CleanShot 2024-01-30 at 12 26 52@2x](https://github.com/whitenia/worldplus-gym-service-site/assets/57860291/c520605e-c36d-4e0f-8be6-4a203fcfe5e4)

**Comment by whitenia-shiraishi** [comment]
こちらありがとうございました！
