### ISSUE TITLE
検索・一覧 - デザイン改修

### ISSUE THREAD

**Issue by whitenia-shiraishi** [whitenia/worldplus-gym-service-site#3]
## ご依頼事項説明動画
https://www.awesomescreenshot.com/video/24046286?key=a1bd44c69acc379cc0b5cd287382b6f7

## Figma
https://www.figma.com/file/wGFKu4XqlUy9fB8Rfw0w1Z/WorldPlus?type=design&node-id=6-2&mode=design&t=G0yHNyrUi51N2FBG-0

**Comment by ShinjiroMoriya** [comment]
現在地で探すページ
https://worldplus-gym.sub.jp/shop/

**Comment by whitenia-shiraishi** [comment]
こちらでOKです。ありがとうございます！
