### ISSUE TITLE
店舗詳細 - デザイン改修

### ISSUE THREAD

**Issue by whitenia-shiraishi** [whitenia/worldplus-gym-service-site#4]
## ご依頼事項説明動画
https://www.awesomescreenshot.com/video/24046607?key=ceaed5be06d1835e8d40129c02a0c2a3

## Figma
https://www.figma.com/file/wGFKu4XqlUy9fB8Rfw0w1Z/WorldPlus?type=design&node-id=776-3672&mode=design&t=OWMeENWWFWmJrFxZ-4

**Comment by ShinjiroMoriya** [comment]
@whitenia-shiraishi 
店舗詳細のデザインはどれがfixしたものかわかりません。

**Comment by whitenia-shiraishi** [comment]
わかりづらくてすみません、
`SP_gym_murashi-koyama_B` をもとに進めていただければと思いますのでよろしくお願いします。
データ整理については加嶋くんに依頼しました。

<img width="490" alt="image" src="https://github.com/whitenia/worldplus-gym-service-site/assets/57860291/4d4dda93-ea0e-453e-812b-93f6887bdb39">


https://www.figma.com/file/wGFKu4XqlUy9fB8Rfw0w1Z/WorldPlus?type=design&node-id=776-3672&mode=design&t=owr2pz6qgfIOmBZP-4

**Comment by ShinjiroMoriya** [comment]
PC側も

**Comment by ShinjiroMoriya** [comment]
混在状況はマイページのAPIをpublicでアクセスできないので、
マイページ側でpublicでアクセスできるようにAPI追加のissue立ててください。

これMT側に曜日毎の項目がありません。
この辺の追加はお願いできますか？
<img width="417" alt="スクリーンショット 2024-01-18 0 23 43" src="https://github.com/whitenia/worldplus-gym-service-site/assets/7581596/cf865571-afa2-415b-b997-d30fe9b14fd9">

あとキャンペーン用の入力項目もですかね。

**Comment by ShinjiroMoriya** [comment]
口コミをサイトに掲載するのは著作権的な問題あるようです。
https://support.google.com/business/thread/139598355/%E5%8F%A3%E3%82%B3%E3%83%9F%E3%82%92%E3%83%9B%E3%83%BC%E3%83%A0%E3%83%9A%E3%83%BC%E3%82%B8%E3%81%AB%E8%A8%98%E8%BC%89%E3%81%99%E3%82%8B%E3%81%AE%E3%81%AF%E5%8F%AF%E8%83%BD%E3%81%A7%E3%81%97%E3%82%87%E3%81%86%E3%81%8B%EF%BC%9F?hl=ja

APIがあるのはあくまで分析のためなんでしょうね。
そもそも表示させるのに結構ややこしい。

**Comment by whitenia-shiraishi** [comment]
@ShinjiroMoriya 
進行ありがとうございます！
返信しますが元気になってからご確認ください。

MTの項目追加については対応します。

> 口コミをサイトに掲載するのは著作権的な問題あるようです。

掲載するとしたら②のやり方ですかね。
あと、Googleの口コミであることや、GBPへの口コミ一覧への導線が必要そうですね。
担当の方にも念のため確認します。
![CleanShot 2024-01-18 at 11 39 16@2x](https://github.com/whitenia/worldplus-gym-service-site/assets/57860291/5cef0f5c-8c42-4156-84ca-339c3b9a1332)

GBPとの連携はニュースのところでもやりたいので、
いずれにしても連携処理は実施したいところではあります。
![CleanShot 2024-01-18 at 11 41 30@2x](https://github.com/whitenia/worldplus-gym-service-site/assets/57860291/edd269f4-f035-456e-9e1c-de19638bf072)

**Comment by ShinjiroMoriya** [comment]
参考になる記事がありました。
https://notes.sharesl.net/articles/2527/

利用するにあたって事前に登録・申請が必要なようです。
あと問題なのが、OAuth認証でアクセストークンを取得する必要がある。
しかもトークンの有効期限があり、一度取れば良いってわけではない。

**Comment by ShinjiroMoriya** [comment]
この口コミ・投稿を取得してサイトに表示しようってなった参考記事とかってありますか？

**Comment by ShinjiroMoriya** [comment]
MTに設備マシンの入力エリアも必要

**Comment by whitenia-shiraishi** [comment]
@ShinjiroMoriya 
すみません、、MTに不慣れで教えてほしいのですが、
以下の部分にスタッフの肩書項目を入れようとしてて、
どこから設定するか教えていただけないですか？
![CleanShot 2024-01-24 at 16 14 19](https://github.com/whitenia/worldplus-gym-service-site/assets/57860291/807759da-ab90-4147-8f77-ec73e974f105)

**Comment by ShinjiroMoriya** [comment]
https://worldplus-gym.sub.jp/_mtadmin/mt.cgi?__mode=view&blog_id=2&_type=content_type&id=3
ここですかね？
僕も正直MTあまりわかってないので、
はっきりとした事言えないです。

**Comment by whitenia-shiraishi** [comment]
ありがとうございます。

ここかなと思いつつ、
ふりかなとか一言とかの入力フィールドが出てこないんです。
なので別であるのかなと思ったのですが見当たらなくて。


![image](https://github.com/whitenia/worldplus-gym-service-site/assets/57860291/51e08726-73b2-4c03-a1fc-4fff5fbf7fa2)

**Comment by whitenia-shiraishi** [comment]
@ShinjiroMoriya 
MTAppjQuery を使ってるんじゃないかという気がしてきました。

https://bit-part.net/products/mtappjquery/
https://www.tam-tam.co.jp/tipsnote/cms/post12567.html

設定でuser.jsというのを編集する必要があるようなのですが、
それがどこにあるのかがまだわかってない状況です。

**Comment by whitenia-shiraishi** [comment]
わかりました、ここでした。
https://worldplus-gym.sub.jp/_mtadmin/mt.cgi?__mode=view&_type=template&id=106&blog_id=2

**Comment by whitenia-shiraishi** [comment]
追加して再構築したのですが、編集画面に表示されずでして、、謎です。
![CleanShot 2024-01-24 at 18 04 43](https://github.com/whitenia/worldplus-gym-service-site/assets/57860291/e58d980f-ead6-44e0-b629-2ee48952c73e)

**Comment by whitenia-shiraishi** [comment]
@ShinjiroMoriya 
時間差で再ログインしたら出てきました！

![CleanShot 2024-01-25 at 16 58 53](https://github.com/whitenia/worldplus-gym-service-site/assets/57860291/0e683b26-d6cd-4358-b23a-5e3b3b7303e1)

この調子で他の項目も追加するので少々お待ちいただけますでしょうか。

口コミのところはもう少し検討しつつ
一旦API取得の申請をやるので、
初期ではリリース見送りになりました。

**Comment by ShinjiroMoriya** [comment]
もともと出ているフィールドには追加されずで、
「フィールドを追加」ってボタンを押して、追加すると出てきますね。
これ既存データを調整するとなると結構大変ですね。

**Comment by ShinjiroMoriya** [comment]
ふりがなっていう項目を肩書として扱うでもいい気がしますね。
ラベルを変えるとかならそのままでもいけるのかな。

**Comment by whitenia-shiraishi** [comment]
@ShinjiroMoriya 

> ふりがなっていう項目を肩書として扱うでもいい気がしますね。

ふりがなを肩書に変更しました。

> これMT側に曜日毎の項目がありません

スタッフ対応時間を編集する項目を追加しました。
以下にデータ足してみたのでこちらで問題なさそうか確認いただけるとありがたいです。

https://worldplus-gym.sub.jp/_mtadmin/mt.cgi?__mode=view&content_type_id=3&_type=content_data&id=438&blog_id=2

![CleanShot 2024-01-29 at 11 28 43](https://github.com/whitenia/worldplus-gym-service-site/assets/57860291/b1e55ae0-1e8c-4731-afd8-bf802a89a5bf)

**Comment by ShinjiroMoriya** [comment]
あとマシンの項目もお願いします。

今組み込んでいて、今日中には組み込めると思います。

**Comment by whitenia-shiraishi** [comment]
わかりました！ありがとうございます！

マシンについてもこれから準備します。

**Comment by whitenia-shiraishi** [comment]
@ShinjiroMoriya 
おまたせいたしました。

武蔵小山店でデータ追加してみたので
こちらで確認してみていただけますと幸いです。

![CleanShot 2024-01-29 at 13 51 16](https://github.com/whitenia/worldplus-gym-service-site/assets/57860291/ef5af09a-33b2-4019-b942-19b9fa634eb2)

**Comment by ShinjiroMoriya** [comment]
https://worldplus-gym.sub.jp/shop/musashikoyama.html
テンプレート反映しました。

**Comment by whitenia-shiraishi** [comment]
反映ありがとうございます！

いい感じです！
後ほど細かく確認しますので、調整の相談あればissueでご連絡します。

**Comment by whitenia-shiraishi** [comment]
@ShinjiroMoriya 
車アクセスの表示エリアがなかったのでこちら追加いただけると幸いです。

![CleanShot 2024-01-29 at 21 36 38](https://github.com/whitenia/worldplus-gym-service-site/assets/57860291/81670dae-7c08-4fca-b808-a1a26e5eb674)

**Comment by whitenia-shiraishi** [comment]
@ShinjiroMoriya 
SP版のページ下部の余白と、
ボタンにアイコンが重なっているので調整をお願いできますでしょうか。

![CleanShot 2024-01-29 at 21 39 01](https://github.com/whitenia/worldplus-gym-service-site/assets/57860291/10396beb-e377-48cd-be62-e8e8e7620b4d)

**Comment by ShinjiroMoriya** [comment]
<img width="898" alt="スクリーンショット 2024-01-29 22 10 44" src="https://github.com/whitenia/worldplus-gym-service-site/assets/7581596/7b205584-1e30-4dd2-a43f-c02f58da8d41">
mt上でフィールドを追加したら表示されます。

**Comment by ShinjiroMoriya** [comment]
もろもろ調整しました。
「見学の申し込み」のリンクは現状正しいものですか？
「入会の申し込み」と同じです。

**Comment by whitenia-shiraishi** [comment]
@ShinjiroMoriya 
諸々調整ありがとうございました！

> 店舗情報 → アクセス

こちら言葉足らずですみません、
Mapの位置へのページ内リンクでお願いしてもよいでしょうか？

それ以外はOKです。

![CleanShot 2024-01-30 at 07 24 55](https://github.com/whitenia/worldplus-gym-service-site/assets/57860291/643cf35f-1d6c-49a5-b08b-b0498d9965ad)

**Comment by ShinjiroMoriya** [comment]
再構築しました。

**Comment by whitenia-shiraishi** [comment]
調整いただきありがとうございます！確認しましたのでクローズします。

**Comment by whitenia-shiraishi** [comment]
ご参考までに元々以下のような処理になっていました！

```
              <mt:ContentField content_field="見学予約フォーム">
              <div class="localnav__block">
                <a class="localnav__block--reserve" href="<mt:If name="reserve_form_url"><mt:Var name="reserve_form_url"><mt:Else>/membership/form.html?shop=<mt:Var name="this_shop_longname">&shop_id=<$mt:EntryID$></mt:If>">
                  見学予約
                </a>
              </div>
```

**Comment by ShinjiroMoriya** [comment]
テンプレート反映しました。

**Comment by whitenia-shiraishi** [comment]
さっそくありがとうございます！
