### ISSUE TITLE
入会とご利用登録のご案内 - デザイン改修

### ISSUE THREAD

**Issue by whitenia-shiraishi** [whitenia/worldplus-gym-service-site#5]
お手数ですがこちら調整進めていただけるとありがたいです。
https://worldplus-gym.sub.jp/join/

https://www.figma.com/file/wGFKu4XqlUy9fB8Rfw0w1Z/WorldPlus?type=design&node-id=947-3659&mode=design&t=fs0U1K8E1x6Ra5Xo-4

**Comment by ShinjiroMoriya** [comment]
https://worldplus-gym.sub.jp/join/

反映しました。

**Comment by whitenia-shiraishi** [comment]
こちらも完了です。ありがとうございます！
