### ISSUE TITLE
トップ - ボタンにリンクを設置したい

### ISSUE THREAD

**Issue by whitenia-shiraishi** [whitenia/worldplus-gym-service-site#6]
ワールドさんより、ボタンの部分のリンク設定をなおしてもらえないかと相談あり、
いけそうでしたら調整をお願いしても良いでしょうか？

![CleanShot 2024-01-29 at 21 25 34](https://github.com/whitenia/worldplus-gym-service-site/assets/57860291/5792ed15-2635-4f72-9304-bc339116d54e)

**Comment by ShinjiroMoriya** [comment]
リンクの指定ください。
差し替えます。

**Comment by ShinjiroMoriya** [comment]
もともと設定はされていたが、
htmlとcssの問題でうまく機能していなかったようです。
改善して反映済みです。

**Comment by whitenia-shiraishi** [comment]
バッチリです！ありがとうございます！
