### ISSUE TITLE
店舗詳細 - 会員カード発行手数料の行を削除

### ISSUE THREAD

**Issue by whitenia-shiraishi** [whitenia/worldplus-gym-service-site#7]
会員カードは発行しないようになったので、
行ごと非表示にしていただけるとありがたいです。

![CleanShot 2024-01-29 at 21 30 06](https://github.com/whitenia/worldplus-gym-service-site/assets/57860291/bc4c5e8b-b021-4549-a95a-af659a8b60ee)

**Comment by ShinjiroMoriya** [comment]
除去しました。

テンプレート
common_functions

**Comment by whitenia-shiraishi** [comment]
確認しました。ありがとうございます！
