### ISSUE TITLE
リリース素材

### ISSUE THREAD

**Issue by ShinjiroMoriya** [whitenia/worldplus-gym-service-site#8]
### css
- common/css/shop_detail.css
- common/css/home.css
- common/css/main.css
- common/css/join.css
- common/css/shop.css

### js
- common/js/main.js

### images
- images/intro_image_pc01@2x.jpg (上書き)
- images/intro_image_pc02@2x.jpg (上書き)
- images/intro_image_pc03@2x.jpg (上書き)
- images/intro_image_pc04@2x.jpg (上書き)
- images/intro_image_sp01@2x.jpg (上書き)
- images/intro_image_sp02@2x.jpg (上書き)
- images/intro_image_sp03@2x.jpg (上書き)
- images/intro_image_sp04@2x.jpg (上書き)

- common/img/title_flow_black.svg
- common/img/flow-visit-img1.png
- common/img/flow-web-img1.png
- common/img/flow-visit-img2.png
- common/img/flow-web-img3.png
- common/img/flow-web-img2.png
- common/img/flow-web-img4.png
- common/img/cover_image_join_pc@2x.jpg
- common/img/cover_image_join_sp@02x.jpg
- common/img/sns/x-logo.svg
- common/img/sns/insta-logo.svg
- common/img/sns/fb-logo.svg

- flexibleSearch/loading.gif

## テンプレート

HOME
https://worldplus-gym.sub.jp/_mtadmin/mt.cgi?__mode=view&_type=template&id=91&blog_id=2

common/json/shop.json
https://worldplus-gym.sub.jp/_mtadmin/mt.cgi?__mode=view&_type=template&id=98&blog_id=2

shop_エリアから探す
https://worldplus-gym.sub.jp/_mtadmin/mt.cgi?__mode=view&_type=template&id=99&blog_id=2

shop_駅名・地名から探す
https://worldplus-gym.sub.jp/_mtadmin/mt.cgi?__mode=view&_type=template&id=101&blog_id=2

shop_現在地から探す（新店舗を探すトップ）
https://worldplus-gym.sub.jp/_mtadmin/mt.cgi?__mode=view&_type=template&id=97&blog_id=2

店舗詳細
https://worldplus-gym.sub.jp/_mtadmin/mt.cgi?__mode=view&_type=template&id=105&blog_id=2

共通ヘッダー
https://worldplus-gym.sub.jp/_mtadmin/mt.cgi?__mode=view&_type=template&id=88&blog_id=2

home_ワールドプラスジムの特徴
https://worldplus-gym.sub.jp/_mtadmin/mt.cgi?__mode=view&_type=template&id=102&blog_id=2

common_functions
https://worldplus-gym.sub.jp/_mtadmin/mt.cgi?__mode=view&_type=template&id=87&blog_id=2

## 静的ページ
入会と利用登録のご案内
- cover_HTML
- 本文
- head追記コード
https://worldplus-gym.sub.jp/_mtadmin/mt.cgi?__mode=view&blog_id=2&_type=content_data&id=65&content_type_id=2

**Comment by ShinjiroMoriya** [comment]
[world-plus-gym-website.zip](https://github.com/whitenia/worldplus-gym-service-site/files/14091648/world-plus-gym-website.zip)

トップの画像はのちほど差し替え、それに伴い
HOMEテンプレート、home.cssの差し替えが必要

**Comment by whitenia-shiraishi** [comment]
まとめていただいて大変助かります！

**Comment by ShinjiroMoriya** [comment]
[world-plus-gym-website.zip](https://github.com/whitenia/worldplus-gym-service-site/files/14092915/world-plus-gym-website.zip)
